---
- name: "Read Env variables"
    ansible_included_var_files: "{{ PROJECT }}_{{ ENV }}.yml"
- name: Provision EC2 instance
  ec2:
     key_name: "{{ key_name }}"
     instance_type: "{{ instance_type }}"
     image: "{{ image }}"
     region: "{{ region }}"
     group_id: "{{ group_id }}"
     count: "{{ count }}"
     vpc_subnet_id: "{{ vpc_subnet_id }}"
     assign_public_ip: "{{ assign_public_ip }}"
     instance_tags:
       Name: "{{ Name }}"
     wait_timeout: "{{ wait_timeout }}"
